name: Base PR

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  base-pr:
    if: github.repository != 'vinkashq/base'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: "base"
          fetch-depth: 0
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/vinkashq/base.git
          git fetch upstream
      - name: Merge Upstream
        run: |
          git merge upstream/main --no-edit
          git push origin base
      - name: Create PR
        run: |
          if [ $(git rev-parse base) != $(git rev-parse origin/main) ]; then
            gh pr view base --base main || gh pr create \
              --title "Merge base changes" \
              --body "Auto PR for Upstream Changes" \
              --base main \
              --head base
          else
            echo "No changes to merge."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
